### ISSUE TITLE
3d plotting Handle 500 error from sample endpoint

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/incore-ui#74]
3d preview breaks if invalid sample data returned
```
plotting.js:12          POST https://incore.ncsa.illinois.edu/plotting/api/samples 500
(anonymous) @ plotting.js:12
w @ runtime.js:65
(anonymous) @ runtime.js:303
C.forEach.t.<computed> @ runtime.js:117
Lb @ main.2a4fca1604295f79adce.js:2
a @ main.2a4fca1604295f79adce.js:2
(anonymous) @ main.2a4fca1604295f79adce.js:2
(anonymous) @ main.2a4fca1604295f79adce.js:2
Bb @ main.2a4fca1604295f79adce.js:2
Fb @ plotting.js:10
(anonymous) @ DFR3Viewer.jsx:539
w @ runtime.js:65
(anonymous) @ runtime.js:303
C.forEach.t.<computed> @ runtime.js:117
Cx @ main.2a4fca1604295f79adce.js:2
a @ main.2a4fca1604295f79adce.js:2
(anonymous) @ main.2a4fca1604295f79adce.js:2
(anonymous) @ main.2a4fca1604295f79adce.js:2
(anonymous) @ main.2a4fca1604295f79adce.js:2
(anonymous) @ DFR3Viewer.jsx:359
w @ runtime.js:65
(anonymous) @ runtime.js:303
C.forEach.t.<computed> @ runtime.js:117
Cx @ main.2a4fca1604295f79adce.js:2
a @ main.2a4fca1604295f79adce.js:2
(anonymous) @ main.2a4fca1604295f79adce.js:2
(anonymous) @ main.2a4fca1604295f79adce.js:2
(anonymous) @ main.2a4fca1604295f79adce.js:2
onClick @ DFR3CurvesGroupList.jsx:15
l @ react-dom.production.min.js:14
f @ react-dom.production.min.js:15
(anonymous) @ react-dom.production.min.js:15
O @ react-dom.production.min.js:17
P @ react-dom.production.min.js:18
T @ react-dom.production.min.js:18
A @ react-dom.production.min.js:21
Ei @ react-dom.production.min.js:84
Ms @ react-dom.production.min.js:250
zt @ react-dom.production.min.js:39
Mi @ react-dom.production.min.js:86
(anonymous) @ react-dom.production.min.js:251
e.unstable_runWithPriority @ scheduler.production.min.js:18
Ds @ react-dom.production.min.js:251
Ti @ react-dom.production.min.js:85
Show 14 more frames
react-dom.production.min.js:198 TypeError: Cannot read properties of null (reading 'length')
    at p.value (DFR3Viewer.jsx:835:48)
```

**Comment by navarroc** [comment]
It would be good to address this in the next milestone (1.5.0) since it breaks the view page.

**Comment by navarroc** [comment]
Here are steps to break this. 

1. Go to DFR3Viewer and select Hazard Type as Hurricane
2. Click on the 4th one down on the DFR3  Curves list

I see the following exception in the console:

`
DFR3Viewer.jsx:1074 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'length')
    at p.value (DFR3Viewer.jsx:1074:45)
    at Co (react-dom.production.min.js:173:192)
    at ko (react-dom.production.min.js:172:264)
    at Po (react-dom.production.min.js:180:30)
    at Bs (react-dom.production.min.js:232:22)
    at Hs (react-dom.production.min.js:233:284)
    at Ca (react-dom.production.min.js:249:348)
    at Ea (react-dom.production.min.js:248:144)
    at ba (react-dom.production.min.js:245:332)
    at Vs (react-dom.production.min.js:243:86)
`

**Comment by longshuicy** [comment]
This is no longer an issue. The 500 error doesn't cause the frontend to break; instead, the preview button is just disabled.

<img width="1201" alt="Image" src="https://github.com/user-attachments/assets/0fababa1-dd6f-4bbe-8f87-c6dbdadd9e03" />
