### ISSUE TITLE
[BUG] error in redirecting to front page after logging in

### ISSUE THREAD

**Issue by ywkim312** [IN-CORE/incore-ui#89]
The front page doesn't get loaded after logging in. This only happens in tst cluster... It complains about the allocation data. This might be related to the update of allocation database...
```
Failed to load resource: the server responded with a status of 403 ()
/space/api/allocations:1          Failed to load resource: the server responded with a status of 403 ()
react-dom.production.min.js:198 TypeError: Cannot read properties of undefined (reading 'total_file_size_of_datasets_byte')
    at w.value (App.jsx:279:70)
    at Or (react-dom.production.min.js:173:192)
    at Cr (react-dom.production.min.js:172:264)
    at Pr (react-dom.production.min.js:180:30)
    at Ba (react-dom.production.min.js:232:22)
    at Ha (react-dom.production.min.js:233:284)
    at Os (react-dom.production.min.js:249:348)
    at Es (react-dom.production.min.js:248:144)
    at Ms (react-dom.production.min.js:250:420)
    at Object.notify (Subscription.js:23:7)
ra @ react-dom.production.min.js:198
App.jsx:279 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'total_file_size_of_datasets_byte')
    at w.value (App.jsx:279:70)
    at Or (react-dom.production.min.js:173:192)
    at Cr (react-dom.production.min.js:172:264)
    at Pr (react-dom.production.min.js:180:30)
    at Ba (react-dom.production.min.js:232:22)
    at Ha (react-dom.production.min.js:233:284)
    at Os (react-dom.production.min.js:249:348)
    at Es (react-dom.production.min.js:248:144)
    at Ms (react-dom.production.min.js:250:420)
    at Object.notify (Subscription.js:23:7)
```

**Comment by navarroc** [comment]
Could this be a bug in our service deployment? When I call the endpoint spaces/api/allocations from a rest client, I get the following:

"Your authentication information doesn't have the x-auth-userinfo header with the request. It is needed to verify the user's privileges"

Shouldn't this be added by incore-auth? Maybe it's a bug in the version of incore-auth we have deployed on incore-tst.

**Comment by ywkim312** [comment]
> Could this be a bug in our service deployment? When I call the endpoint spaces/api/allocations from a rest client, I get the following:
> 
> "Your authentication information doesn't have the x-auth-userinfo header with the request. It is needed to verify the user's privileges"
> 
> Shouldn't this be added by incore-auth? Maybe it's a bug in the version of incore-auth we have deployed on incore-tst.

I have done several test, checking the keycloak token, incore-services, and incore-auth and every test were okay and I am suspecting the the traefik is probably the reason and asked Rob to check it out. According to him, it might be because of traefik2 that we are using for tst clusters, whereas others are using traefik1

**Comment by ywkim312** [comment]
This is not a problem of incore-ui so I close it from here and open the same one in platform
